// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.DataAccess.Data;

#nullable disable

namespace Shop.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230624124555_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Platforming"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Souls-like"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Rouge-lite"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "MMO"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Price100")
                        .HasColumnType("REAL");

                    b.Property<double>("Price50")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Prepare to live",
                            Developer = "Form Hardware",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 49.990000000000002,
                            Publisher = "Nandai Bamco",
                            Title = "Bright Souls"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Prepare to live again",
                            Developer = "Form Hardware",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 49.990000000000002,
                            Publisher = "Nandai Bamco",
                            Title = "Bright Souls 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prepere to die",
                            Developer = "Form Hardware, Bimtendo, Circle Enix, Bugisoft, Icestorm, DVD Projekt BLUE, Altus",
                            Price = 69.989999999999995,
                            Price100 = 49.990000000000002,
                            Price50 = 59.990000000000002,
                            Publisher = "NASA",
                            Title = "Dean Simulator"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The sequel to the critically acclaimed masterpiece Dean Simulator",
                            Developer = "Form Hardware, Bimtendo, Circle Enix, Bugisoft, Icestorm, DVD Projekt BLUE, Altus",
                            Price = 69.989999999999995,
                            Price100 = 49.990000000000002,
                            Price50 = 59.990000000000002,
                            Publisher = "NASA",
                            Title = "Dean Simulator - Revenge"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hardest game ever - IGN",
                            Developer = "Dean",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 49.990000000000002,
                            Publisher = "Dean",
                            Title = "Student Simulator 2023"
                        },
                        new
                        {
                            Id = 6,
                            Description = "One of the most well known games in the whole universe",
                            Developer = "Bimtendo",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 49.990000000000002,
                            Publisher = "Bimtendo",
                            Title = "Super Maria Sisters"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Game of the Year, every year",
                            Developer = "Bimtendo",
                            Price = 59.990000000000002,
                            Price100 = 39.990000000000002,
                            Price50 = 49.990000000000002,
                            Publisher = "Bimtendo",
                            Title = "Super Maria Sisters 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
